-- Log Count Summary Query for All Tables
-- This query aggregates log counts by hour for all specified tables
-- Generated by Terraform templatefile() function


SELECT
    '${table_names[0]}' as table_name,
    partition_0 as year,
    partition_1 as month,
    partition_2 as day,
    partition_3 as hour,
    COUNT(*) as log_count
FROM ${database_name}."${table_names[0]}"
WHERE partition_0 = cast(year(current_date) as varchar)
    AND partition_1 = lpad(cast(month(current_date) as varchar), 2, '0')
    AND partition_2 = lpad(cast(day(current_date) as varchar), 2, '0')
    AND partition_4 = '${partition_4_value}'
GROUP BY partition_0, partition_1, partition_2, partition_3

UNION ALL

SELECT
    '${table_names[1]}' as table_name,
    partition_0 as year,
    partition_1 as month,
    partition_2 as day,
    partition_3 as hour,
    COUNT(*) as log_count
FROM ${database_name}."${table_names[1]}"
WHERE partition_0 = cast(year(current_date) as varchar)
    AND partition_1 = lpad(cast(month(current_date) as varchar), 2, '0')
    AND partition_2 = lpad(cast(day(current_date) as varchar), 2, '0')
    AND partition_4 = '${partition_4_value}'
GROUP BY partition_0, partition_1, partition_2, partition_3

UNION ALL

SELECT
    '${table_names[2]}' as table_name,
    partition_0 as year,
    partition_1 as month,
    partition_2 as day,
    partition_3 as hour,
    COUNT(*) as log_count
FROM ${database_name}."${table_names[2]}"
WHERE partition_0 = cast(year(current_date) as varchar)
    AND partition_1 = lpad(cast(month(current_date) as varchar), 2, '0')
    AND partition_2 = lpad(cast(day(current_date) as varchar), 2, '0')
    AND partition_4 = '${partition_4_value}'
GROUP BY partition_0, partition_1, partition_2, partition_3

ORDER BY table_name, year, month, day, hour;
